version: 2

jobs:
  checkout:
    docker:
      - image: circleci/node:10.15.3

    steps:
      # Init
      - checkout

      - run:
          name: Update NPM
          command: |
            sudo npm install -g lerna
            sudo npm install -g npm

      - restore_cache:
          keys:
            - v1-cache-{{ checksum "package.json" }}
            - v1-cache-

      - run: npm install
      - run: lerna bootstrap

      - save_cache:
          paths:
            - node_modules
          key: v1-cache-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: /home/circleci
          paths:
            - project

  audit:
    docker:
      - image: circleci/node:10.15.3

    steps:
      - attach_workspace:
          at: ~/

      - run:
          name: NPM Audit
          command: |
            npm run ci:audit

  lint:
    docker:
      - image: circleci/node:10.15.3

    steps:
      - attach_workspace:
          at: ~/

      - run: npm run lint

  format:
    docker:
      - image: circleci/node:10.15.3

    steps:
      - attach_workspace:
          at: ~/

      - run: npm run format

workflows:
  version: 2

  test:
    jobs:
      - checkout:
      - audit:
          requires:
            - checkout
      - lint:
          requires:
            - checkout
      - format:
          requires:
            - checkout
